service: bingo-project

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1
  timeout: 30

functions:
  getCard:
    handler: src/handlers/api.getCard
    timeout: 30
    events:
      - http:
          path: card
          method: get
          cors: true
  getNextNumber:
    handler: src/handlers/api.getNextNumber
    timeout: 30
    events:
      - http:
          path: call-number
          method: get
          cors: true
  verifyBingo:
    handler: src/handlers/api.verifyBingo
    timeout: 30
    events:
      - http:
          path: check-bingo
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3000
